version: '3.8'
services: 
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/Data:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_SECRET_KEY=secret_key
      - PROMETHEUS_URL=http://prometheus:9090
    depends_on: 
      - prometheus

  